<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class LaporanAgendaModel extends CI_Model {

	public function getJson($jenis=""){
		$data = $this->db->query("SELECT a.ID_AGENDA_RUANG_RAPAT, a.ID_JENIS_KEGIATAN, a.PEMESAN, a.ID_ASAL_KEGIATAN, a.ID_RUANG_RAPAT, convert(varchar(20), TGL_PEMESANAN, 120) as TGL_PEMESANAN, a.KETERANGAN, a.JUMLAH, convert(varchar(20), a.TGL_MULAI, 120) as TGL_MULAI, convert(varchar(20), a.TGL_SELESAI, 120) as TGL_SELESAI, b.RUANG_RAPAT ID_RUANG_RAPAT_DESC, c.nama_lengkap PEMESAN_DESC, d.JENIS_KEGIATAN ID_JENIS_KEGIATAN_DESC, e.ASAL_KEGIATAN ID_ASAL_KEGIATAN_DESC FROM TBL_AGENDA_RUANG_RAPAT a JOIN TBL_M_RUANG_RAPAT b ON a.ID_RUANG_RAPAT=b.ID_RUANG_RAPAT JOIN KARYAWAN c ON a.PEMESAN=c.nip JOIN TBL_M_JENIS_KEGIATAN d ON a.ID_JENIS_KEGIATAN=d.ID_JENIS_KEGIATAN JOIN TBL_M_ASAL_KEGIATAN e ON a.ID_ASAL_KEGIATAN=e.ID_ASAL_KEGIATAN");
		return $data->result();
	}

}
