<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class LaporanAgendaModel extends CI_Model {

	public function getJson($jenis=""){
		$data = $this->db->query("SELECT A.TGL_PEMESANAN, B.JENIS_KEGIATAN, C.ASAL_KEGIATAN, D.nama_lengkap AS PEMESAN, A.KETERANGAN, A.JUMLAH, E.RUANG_RAPAT, A.TGL_MULAI, A.TGL_SELESAI FROM TBL_AGENDA_RUANG_RAPAT A
		LEFT JOIN TBL_M_JENIS_KEGIATAN B ON A.ID_JENIS_KEGIATAN = B.ID_JENIS_KEGIATAN
		LEFT JOIN TBL_M_ASAL_KEGIATAN C ON A.ID_ASAL_KEGIATAN = C.ID_ASAL_KEGIATAN
		LEFT JOIN KARYAWAN D ON A.PEMESAN = D.nip
		LEFT JOIN TBL_M_RUANG_RAPAT E ON A.ID_RUANG_RAPAT = E.ID_RUANG_RAPAT
		ORDER BY TGL_PEMESANAN DESC");
		return $data->result();
	}

}
